export {
  RESEARCHER_LIMITS,
  ResearcherProposalSchema,
  ResearcherReferenceSchema,
  ResearcherPacketSchema,
  compileResearcherOutputSchema,
  createResearcherAgent,
  isHealthySearchReceipt,
  loadResearcherOutputSchema,
  runResearcher,
  validateResearcherProposal,
  type CreateResearcherAgentOptions,
  type ResearcherAgent,
  type ResearcherError,
  type ResearcherFacetSupport,
  type ResearcherPacket,
  type ResearcherPropose,
  type ResearcherProposeContext,
  type ResearcherProposal,
  type ResearcherReference,
  type ValidateResearcherProposalOptions,
} from "./researcher-agent.js";
export {
  EVIDENCE_CRITIC_LIMITS,
  EvidenceCriticProposalSchema,
  createEvidenceCriticAgent,
  runEvidenceCritic,
  validateEvidenceCriticProposal,
  type CreateEvidenceCriticAgentOptions,
  type EvidenceCriticAgent,
  type EvidenceCriticError,
  type EvidenceCriticProposal,
  type EvidenceCriticPropose,
  type EvidenceCriticProposeContext,
  type ValidateEvidenceCriticOptions,
} from "./evidence-critic-agent.js";

// T-32-01 — Claim Extractor (validate-only; apply via ClaimRepository.create is a follow-up)
export {
  CLAIM_EXTRACTOR_LIMITS,
  ClaimExtractorOutputSchema,
  ClaimProposalSchema,
  compileClaimExtractorOutputSchema,
  createClaimExtractorAgent,
  loadClaimExtractorOutputSchema,
  validateClaimExtractorProposal,
  type ClaimExtractorAgent,
  type ClaimExtractorError,
  type ClaimExtractorPropose,
  type ClaimExtractorProposeContext,
  type ClaimProposal,
  type CreateClaimExtractorAgentOptions,
  type ValidateClaimExtractorOptions,
} from "./claim-extractor-agent.js";

// T-32-02 — Claim Reviewer (proposal-only; apply via ClaimReviewService)
export {
  CLAIM_REVIEWER_LIMITS,
  ClaimReviewerOutputSchema,
  compileClaimReviewerOutputSchema,
  createClaimReviewerAgent,
  loadClaimReviewerOutputSchema,
  validateClaimReviewerProposal,
  type ClaimReviewerAgent,
  type ClaimReviewerError,
  type ClaimReviewerProposal,
  type ClaimReviewerPropose,
  type ClaimReviewerProposeContext,
  type ClaimReviewerReviewRow,
  type CreateClaimReviewerAgentOptions,
  type ValidateClaimReviewerOptions,
} from "./claim-reviewer-agent.js";
